version: '3.7'

services:
    revproxy:
        container_name: revproxy
        hostname: revproxy
        image: nginx:stable-alpine-slim
        restart: always
        volumes:
            - ./revproxy:/etc/nginx/conf.d
            - ./certbot/www:/var/www/certbot
            - ./certbot/ssl:/etc/nginx/ssl
        ports:
            - 80:80
            - 443:443
        networks:
            - revproxy-web-network

    certbot:
        container_name: certbot
        hostname: certbot
        image: certbot/certbot:v2.6.0
        volumes:
            - ./certbot/www:/var/www/certbot:rw
            - ./certbot/ssl:/etc/letsencrypt/:rw
        networks:
            - revproxy-web-network

    webphp:
        container_name: webphp
        hostname: webphp
        build:
            context: ./webphp
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - dbphp
        volumes:
            - ./webphp/html:/var/www/html
        environment:
            DB_USER: ${DBPHP_USER}
            DB_PASSWORD: ${DBPHP_PASSWORD}
            DB_NAME: ${DBPHP_DATABASE}
            DB_PORT: ${DBPHP_PORT}
        env_file:
            - ./.env
        expose:
            - ${PHP_PORT}
        networks:
            - revproxy-web-network
            - revproxy-dbphp-network

    dbphp:
        container_name: dbphp
        hostname: dbphp
        image: mariadb:lts
        restart: always
        volumes:
            - webphp-db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DBPHP_ROOT_PASSWORD}
            MYSQL_USER: ${DBPHP_USER}
            MYSQL_PASSWORD: ${DBPHP_PASSWORD}
            MYSQL_DATABASE: ${DBPHP_DATABASE}
        env_file:
            - ./.env
        expose:
            - ${DBPHP_PORT}
        networks:
            - revproxy-dbphp-network

    webnodejs:
        container_name: webnodejs
        hostname: webnodejs
        build:
            context: ./webnodejs
            dockerfile: Dockerfile
        restart: always
        environment:
            NODEJS_PORT: ${NODEJS_PORT}
        expose:
            - ${NODEJS_PORT}
        env_file:
            - ./.env
        networks:
            - revproxy-web-network

    webpython:
        container_name: webpython
        hostname: webpython
        build:
            context: ./webpython
            dockerfile: Dockerfile
        restart: always
        environment:
            PYTHON_PORT: ${PYTHON_PORT}
        env_file:
            - ./.env
        expose:
            - ${PYTHON_PORT}
        networks:
            - revproxy-web-network

volumes:
    webphp-db-data:
        name: webphp-db-data

networks:
    revproxy-web-network:
        name: revproxy-web-network
        driver: bridge

    revproxy-dbphp-network:
        name: revproxy-dbphp-network
        driver: bridge